# Mapping of IPEDS columns to database columns
IPEDS_TO_DB_MAP = {
    "WEBADDR": "website_address",
    "HBCU": "historically_black_college_or_university",
    "TRIBAL": "tribal_college_or_university",
    "ICLEVEL": "program_level",
    "CONTROL": "control",
    "STABBR": "state",
    "INSTSIZE": "institution_size"
}

PROGRAM_LENGTH_MAPPING = {
    "1": "FOUR_OR_MORE_YEARS",
    "2": "AT_LEAST_TWO_BUT_LESS_THAN_FOUR_YEARS",
    "3": "LESS_THAN_TWO_YEARS",
    "-3": "NOT_AVAILABLE"
}

CONTROL_MAPPING = {
    "1": "PUBLIC",
    "2": "PRIVATE_NONPROFIT",
    "3": "PRIVATE_FORPROFIT",
    "-3": "NOT_AVAILABLE"
}

INSTITUTION_SIZE_MAPPING = {
    "1": "UNDER_1000",
    "2": "BETWEEN_1000_AND_4999",
    "3": "BETWEEN_5000_AND_9999",
    "4": "BETWEEN_10000_AND_19999",
    "5": "OVER_20000",
    "-1": "NOT_REPORTED",
    "-2": "NOT_APPLICABLE"
}

# Pulled from carnegieclassifications.acenet.edu
# https://carnegieclassifications.acenet.edu/wp-content/uploads/2023/03/CCIHE2021-PublicData.xlsx
CARNEGIE_CLASSIFICATION_MAPPING = {
    "-2": "NOT_CLASSIFIED_NOT_IN_CLASSIFICATION_UNIVERSE",
    "1": "ASSOCIATES_COLLEGES_HIGH_TRANSFER_HIGH_TRADITIONAL",
    "2": "ASSOCIATES_COLLEGES_HIGH_TRANSFER_MIXED_TRADITIONAL_NONTRADITIONAL",
    "3": "ASSOCIATES_COLLEGES_HIGH_TRANSFER_HIGH_NONTRADITIONAL",
    "4": "ASSOCIATES_COLLEGES_MIXED_TRANSFER_CAREER_TECHNICAL_HIGH_TRADITIONAL",
    "5": "ASSOCIATES_COLLEGES_MIXED_TRANSFER_CAREER_TECHNICAL_MIXED_TRADITIONAL_NONTRADITIONAL",
    "6": "ASSOCIATES_COLLEGES_MIXED_TRANSFER_CAREER_TECHNICAL_HIGH_NONTRADITIONAL",
    "7": "ASSOCIATES_COLLEGES_HIGH_CAREER_TECHNICAL_HIGH_TRADITIONAL",
    "8": "ASSOCIATES_COLLEGES_HIGH_CAREER_TECHNICAL_MIXED_TRADITIONAL_NONTRADITIONAL",
    "9": "ASSOCIATES_COLLEGES_HIGH_CAREER_TECHNICAL_HIGH_NONTRADITIONAL",
    "10": "SPECIAL_FOCUS_TWO_YEAR_HEALTH_PROFESSIONS",
    "11": "SPECIAL_FOCUS_TWO_YEAR_TECHNICAL_PROFESSIONS",
    "12": "SPECIAL_FOCUS_TWO_YEAR_ARTS_DESIGN",
    "13": "SPECIAL_FOCUS_TWO_YEAR_OTHER_FIELDS",
    "14": "BACCALAUREATE_ASSOCIATES_COLLEGES_ASSOCIATES_DOMINANT",
    "15": "DOCTORAL_UNIVERSITIES_VERY_HIGH_RESEARCH_ACTIVITY",
    "16": "DOCTORAL_UNIVERSITIES_HIGH_RESEARCH_ACTIVITY",
    "17": "DOCTORAL_PROFESSIONAL_UNIVERSITIES",
    "18": "MASTERS_COLLEGES_UNIVERSITIES_LARGER_PROGRAMS",
    "19": "MASTERS_COLLEGES_UNIVERSITIES_MEDIUM_PROGRAMS",
    "20": "MASTERS_COLLEGES_UNIVERSITIES_SMALL_PROGRAMS",
    "21": "BACCALAUREATE_COLLEGES_ARTS_SCIENCES_FOCUS",
    "22": "BACCALAUREATE_COLLEGES_DIVERSE_FIELDS",
    "23": "BACCALAUREATE_ASSOCIATES_COLLEGES_MIXED_BACCALAUREATE_ASSOCIATES",
    "24": "SPECIAL_FOCUS_FOUR_YEAR_FAITH_RELATED_INSTITUTIONS",
    "25": "SPECIAL_FOCUS_FOUR_YEAR_MEDICAL_SCHOOLS_CENTERS",
    "26": "SPECIAL_FOCUS_FOUR_YEAR_OTHER_HEALTH_PROFESSIONS_SCHOOLS",
    "27": "SPECIAL_FOCUS_FOUR_YEAR_RESEARCH_INSTITUTION",
    "28": "SPECIAL_FOCUS_FOUR_YEAR_ENGINEERING_OTHER_TECHNOLOGY_RELATED_SCHOOLS",
    "29": "SPECIAL_FOCUS_FOUR_YEAR_BUSINESS_MANAGEMENT_SCHOOLS",
    "30": "SPECIAL_FOCUS_FOUR_YEAR_ARTS_MUSIC_DESIGN_SCHOOLS",
    "31": "SPECIAL_FOCUS_FOUR_YEAR_LAW_SCHOOLS",
    "32": "SPECIAL_FOCUS_FOUR_YEAR_OTHER_SPECIAL_FOCUS_INSTITUTIONS",
    "33": "TRIBAL_COLLEGES_UNIVERSITIES"
}