name: Build UI image

on:
  push:
    branches: ["main"]
    tags:
      - 'v*.*.*' # glob for semver tags (including prereleases)
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 0 1-31/7 * *'
  workflow_dispatch:

jobs:
  call-build-ui-image:
    uses: osg-htc/build-push/.github/workflows/build-push.yaml@main
    secrets: inherit
    with:
      image: 'hub.opensciencegrid.org/opensciencegrid/topology-institutions-ui'
      file: 'institutions-ui.Dockerfile'
